#!/usr/bin/env bash

#Script for executing leelaz remotely.

set -eu
source ../config.sh
gcloud compute ssh "$INSTANCE_NAME" --zone "$ZONE" --command "/leela/leelaz -g -w /leela/$NETWORK-network.gz -b 0"
