#!/usr/bin/env bash

#Script for executing katago remotely.

set -eu
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "${DIR}/../config.sh"
gcloud compute ssh "$INSTANCE_NAME" --zone "$ZONE" --command "cd /leela && ./katago gtp -model model.txt -config gtp_example.cfg"